### ISSUE TITLE
Joystick Support

### ISSUE THREAD

**Issue by nametable** [scanlime/robot-odyssey-rewired#3]
What would it take to add hardware joystick support to your port of the game? I understand that the x86 binary is being translated to c++ in your port. Does this mean that the port could be compiled to run as a native application on a Linux distribution or Microsoft Windows instead of just in a browser. I am very interested in your port and would be interested in helping add enhancements.

If you could point be in the right direction that would be great. At one point I was trying to remake Robots in Odyssey with SDL for graphics but I never got far.

**Comment by scanlime** [comment]
good idea, there’s a web gamepad api i’ve been meaning to look into.

**Comment by scanlime** [comment]
Checkin 2552cb880120fbe845db11e354fc6814169f9e29 adds basic gamepad support using the browser gamepad API.

From the limited testing I've been able to do with a Steam controller on Mac OS, it is kinda-working in Chrome, Firefox, and Safari, but the button mappings are only completely right on Chrome.

This could obvs benefit from a button mapping UI, but I'm trying to put that off a bit until there's more infrastructure for UI in general.

Let me know if this works, and/or file more specific issues for any problems you come across.

(If you do try this and you've visited the site before, please be sure you're running the latest code rather than the offline cache by reloading the site, closing all browser tabs open to it, then opening it again.)

**Comment by nametable** [comment]
Confirmed to work in Firefox and Chrome with a USB Logitech joystick on Manjaro. I also see the mapping problems you've described in Firefox.

Overall, very good though.
